In [ ]:
import tensorflow as tf

In [ ]:
print(tf.__version__)

2.12.0


In [ ]:
scalar = tf.constant(7)
scalar.ndim
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
vector= tf.constant([10,10])
vector, vector.ndim

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>, 1)

In [ ]:
matrix=tf.constant([[10,10],
                    [10,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [10, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
tensor= tf.constant([[[10,10],
                      [10,10]],
                      [[10,10],
                       [10,10]],
                       [[10,10],
                       [10,10]]])

In [ ]:
tensor

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
unchangeable_tensor= tf.constant(tensor)

In [ ]:
# unchangeable_tensor[0][0][0].assign(9), # The error here means that constant tensors can't be cahnged like variable tensors.

In [ ]:
changeable_tensor = tf.Variable([[10,10],
                                 [10,9]])

In [ ]:
changeable_tensor[0].assign(9)

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=int32, numpy=
array([[ 9,  9],
       [10,  9]], dtype=int32)>

In [ ]:
random= tf.random.Generator.from_seed(42).normal(shape=(2,3))

In [ ]:
random

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ]], dtype=float32)>

## Shuffling the tensors

In [ ]:
unshuffled_tensor=tf.constant([[10,8],
                               [9,5],
                               [3,1]])
unshuffled_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  8],
       [ 9,  5],
       [ 3,  1]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)

In [ ]:
tf.random.set_seed(42)
shuffled_tensor=tf.random.shuffle(unshuffled_tensor, seed=42)
shuffled_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  8],
       [ 9,  5],
       [ 3,  1]], dtype=int32)>

In [ ]:
tensor

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10]]], dtype=int32)>

In [ ]:
import numpy as np

In [ ]:
numpy_A=np.arange(1,25)

In [ ]:
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [ ]:
A = tf.constant(numpy_A, shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int64, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [ ]:
rank_4_tensor = tf.constant(np.zeros(shape=(2,3,4,5), dtype=float))
rank_4_tensor


<tf.Tensor: shape=(2, 3, 4, 5), dtype=float64, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])>

In [ ]:
print(f"the dimensions of the tensor:{rank_4_tensor.ndim}")
print(f"the shape: {rank_4_tensor.shape}")
print(f"The elements along 0 axis:{rank_4_tensor.shape[0]}")
print(f"the last elements:{rank_4_tensor.shape[-1]}")
print(f"The size of the tesnor:{tf.size(rank_4_tensor)}")
print(f"Total number of elemnts in our tensor:{tf.size(rank_4_tensor).numpy()}")

the dimensions of the tensor:4
the shape: (2, 3, 4, 5)
The elements along 0 axis:2
the last elements:5
The size of the tesnor:120
Total number of elemnts in our tensor:120


In [ ]:
rank_4_tensor[:2]

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float64, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])>

In [ ]:
tensor_2=tf.constant(np.arange(11,31), shape=(2,5,2))

In [ ]:
tensor_2

<tf.Tensor: shape=(2, 5, 2), dtype=int64, numpy=
array([[[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]],

       [[21, 22],
        [23, 24],
        [25, 26],
        [27, 28],
        [29, 30]]])>

In [ ]:
tensor_2[1:2, 2:3,-1]

<tf.Tensor: shape=(1, 1), dtype=int64, numpy=array([[26]])>

In [ ]:
tensor_3= tensor_2[..., tf.newaxis]

In [ ]:
tensor_3

<tf.Tensor: shape=(2, 5, 2, 1), dtype=int64, numpy=
array([[[[11],
         [12]],

        [[13],
         [14]],

        [[15],
         [16]],

        [[17],
         [18]],

        [[19],
         [20]]],


       [[[21],
         [22]],

        [[23],
         [24]],

        [[25],
         [26]],

        [[27],
         [28]],

        [[29],
         [30]]]])>

In [ ]:
tf.expand_dims(tensor_2, axis=2)

<tf.Tensor: shape=(2, 5, 1, 2), dtype=int64, numpy=
array([[[[11, 12]],

        [[13, 14]],

        [[15, 16]],

        [[17, 18]],

        [[19, 20]]],


       [[[21, 22]],

        [[23, 24]],

        [[25, 26]],

        [[27, 28]],

        [[29, 30]]]])>

## Matrix Operations

### Addition

In [ ]:
matrix_1=tf.constant([[1,2],
                      [3,4],
                      [5,6]])
matrix_2= tf.constant([[1,2],
                       [3,4],
                       [5,6]])
matrix_1.shape, matrix_2.shape

(TensorShape([3, 2]), TensorShape([3, 2]))

In [ ]:
%%time
matrix_1 + matrix_2

CPU times: user 2.02 ms, sys: 0 ns, total: 2.02 ms
Wall time: 2.32 ms


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  4],
       [ 6,  8],
       [10, 12]], dtype=int32)>

**Note**: we can use the usual way of operations on matrices like the above but using `tf.math` will perform the operation much faster as `tensorflow()` is able to use GPU.
Let's see what I mean:

In [ ]:
%%time
tf.math.add(matrix_1, matrix_2)

CPU times: user 243 µs, sys: 32 µs, total: 275 µs
Wall time: 285 µs


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  4],
       [ 6,  8],
       [10, 12]], dtype=int32)>

You can see the difference now!!!

In [ ]:
# tf.matmul(matrix_1, matrix_2) #If you run this cell it will give you error "Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul]"

Matrix has two rules for multiplication:
* The inner dimensions must match
* The resultant matrix will be the shape of outside dimensions.

So lets `reshape()` or `transpose()` our matrices. `transpose()` is required by `tf.tensordot()`.

In [ ]:
matrix_1.shape, matrix_2.shape

(TensorShape([3, 2]), TensorShape([3, 2]))

In [ ]:
tf.matmul(matrix_1, tf.transpose(matrix_2))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]], dtype=int32)>

In [ ]:
tf.matmul(tf.reshape(matrix_1, shape=(2,3)), matrix_2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 28],
       [49, 64]], dtype=int32)>

In [ ]:
tf.divide(matrix_1, matrix_2)

<tf.Tensor: shape=(3, 2), dtype=float64, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]])>

Well you can't divide matrices 😆. This was just aiwein krraha thaa 😆

In [ ]:
tf.tensordot(matrix_1, tf.transpose(matrix_2), axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]], dtype=int32)>

In [ ]:
tf.tensordot(tf.transpose(matrix_1), matrix_2, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[35, 44],
       [44, 56]], dtype=int32)>

## Changing datatypes of Tensors:
Typecasting in tensorflow is by `tf.cast()`.

In [ ]:
A= tf.constant([1,2,3])
A

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
B=tf.constant([9.,8.,10.])
B

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 9.,  8., 10.], dtype=float32)>

In [ ]:
C= tf.cast(A, tf.int8)
C

<tf.Tensor: shape=(3,), dtype=int8, numpy=array([1, 2, 3], dtype=int8)>

In [ ]:
D=tf.cast(B, tf.float16)
D

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([ 9.,  8., 10.], dtype=float16)>

In [ ]:
E= tf.cast(D, tf.int64)

In [ ]:
E

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([ 9,  8, 10])>

## Aggregating Tensors:
Condensing them from multiple values down to smaller values

In [ ]:
print(-D)

tf.Tensor([ -9.  -8. -10.], shape=(3,), dtype=float16)


In [ ]:
F= tf.abs(-D) #gives the absolute value
F

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([ 9.,  8., 10.], dtype=float16)>

In [ ]:
tf.reduce_min(E) #minimum

<tf.Tensor: shape=(), dtype=int64, numpy=8>

In [ ]:
tf.reduce_max(D) # to find maximum

<tf.Tensor: shape=(), dtype=float16, numpy=10.0>

In [ ]:
tf.reduce_mean(F) #to find mean

<tf.Tensor: shape=(), dtype=float16, numpy=9.0>

In [ ]:
# tf.math.reduce_variance(E) #wont work so will have to convert dtype into float

In [ ]:
tf.math.reduce_variance(tf.cast(E, tf.float32)) # to find variance

<tf.Tensor: shape=(), dtype=float32, numpy=0.6666667>

In [ ]:
tf.math.reduce_std(tf.cast(E, tf.float32)) # to find standard deviation

<tf.Tensor: shape=(), dtype=float32, numpy=0.8164966>

In [ ]:
import tensorflow_probability as tfp

In [ ]:
tfp.stats.variance(tf.cast(E, tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=0.6666667>

## Finding positional maximum and minimum

In [ ]:
tf.random.set_seed(50)
G=tf.constant(tf.random.uniform(shape=[50],seed=42))
G

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6203257 , 0.89154935, 0.32661438, 0.97836685, 0.7686428 ,
       0.74070084, 0.645759  , 0.7121906 , 0.7831063 , 0.5153687 ,
       0.42817783, 0.5632707 , 0.01776755, 0.7162845 , 0.46074605,
       0.61696136, 0.36191297, 0.986956  , 0.27285445, 0.5927348 ,
       0.68023896, 0.54652536, 0.28453124, 0.82896054, 0.5145595 ,
       0.88879526, 0.54013336, 0.2245214 , 0.5683669 , 0.56679094,
       0.41150737, 0.70246565, 0.46915042, 0.5505512 , 0.23332906,
       0.3555416 , 0.8680407 , 0.7273568 , 0.29180384, 0.35253668,
       0.8352454 , 0.480016  , 0.84876597, 0.83687925, 0.15508807,
       0.8417727 , 0.78756   , 0.2899896 , 0.9872377 , 0.7657682 ],
      dtype=float32)>

In [ ]:
tf.reduce_max(G)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9872377>

In [ ]:
tf.argmax(G).numpy()

48

In [ ]:
G[tf.argmax(G)] # to find the max value by index

<tf.Tensor: shape=(), dtype=float32, numpy=0.9872377>

In [ ]:
G[48]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9872377>

In [ ]:
(tf.reduce_max(G)== G[tf.argmax(G)]).numpy()

True

## Find positional minimum

In [ ]:
tf.reduce_min(G).numpy()

0.017767549

In [ ]:
tf.argmin(G).numpy() #to get the index of min value

12

In [ ]:
G[tf.argmin(G)].numpy()

0.017767549

In [ ]:
(G[tf.argmin(G)]==tf.reduce_min(G)).numpy()

True

## Squeezing and One_hot encoding

In [ ]:
G = tf.reshape(G,shape=(1,1,1,50))

In [ ]:
G.shape

TensorShape([1, 1, 1, 50])

In [ ]:
G_squeezed= tf.squeeze(G)

In [ ]:
G_squeezed.shape #singal dimensional axices are gone

TensorShape([50])

In [ ]:
indices = [1,2,3,4]
depth=4
H=tf.one_hot(indices, depth)
H

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
#lets have some fun with one_hot
H= tf.one_hot(indices, depth, on_value="Yeahhh", off_value="Nahhh")
H

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Nahhh', b'Yeahhh', b'Nahhh', b'Nahhh'],
       [b'Nahhh', b'Nahhh', b'Yeahhh', b'Nahhh'],
       [b'Nahhh', b'Nahhh', b'Nahhh', b'Yeahhh'],
       [b'Nahhh', b'Nahhh', b'Nahhh', b'Nahhh']], dtype=object)>

## Finished Yayyyyyy!!!! 🕺